### ISSUE TITLE
Error: Cannot find module 'app'

### ISSUE THREAD

**Issue by thuongdinh-agilityio** [rosshinkley/nightmare-download-manager#1]
I got the below error when use your package
Error: Cannot find module 'app'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Nightmare.<anonymous> (/src/app/node_modules/nightmare-download-manager/nightmare-download-manager.js:12:15)
    at Nightmare.next (/node_modules/nightmare/lib/nightmare.js:208:12)
    at EventEmitter.<anonymous> (/node_modules/nightmare/lib/nightmare.js:214:12)
    at EventEmitter.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at EventEmitter.emit (events.js:166:7)

**Comment by rosshinkley** [comment]
If you simply run `npm install`, it would try to pull in the regular Nightmare package from NPM.  This won't work as the second argument to `.action()` in Nightmare 2.1.0 is the action to add to the Nightmare instance itself.  On my local box, I had the appropriate branch from my fork symlinked, which didn't get updated in the package.  This has been fixed, please try again and let me know if you have any other problems.
